Topic 1
koma757/Basic-Python pull request #2
Opened 2022-12-01 11:49 UTC by koma757

よろしくお願いします.

2022-12-02 09:05 UTC, DaichiWarasuga commented
AOJ1はA以外完璧です。Aを修正してからもう一度レビュー依頼出してください。

2022-12-02 13:42 UTC, takeshun256 requested changes
03と06をレビューしました！レビューした箇所の修正をお願いします。

2022-12-02 13:42 UTC, takeshun256 commented on AOJ/06/06_A.py
> +    print(ai[i],end=' ')
🟢リストの表示は、単純に書くことができます。
```suggestion
print(*ai)
```

2022-12-02 13:42 UTC, takeshun256 commented on AOJ/06/06_B.py
> +        num[3].remove(int(card[1]))
🟢 `card[0]`や `card[1]` で繰り返しリストから取り出している箇所について、以下のように別々に入力を受け取ることで、リストから何度も参照する必要がなくなります。
```python
char, num = input().split()
```
続く `if` 文の箇所を `char`と`num`で書き直してみてください。

2022-12-02 13:42 UTC, takeshun256 commented on AOJ/06/06_C.py
> +    print(" "," ".join(h_str))
🔴 [AOJ](https://onlinejudge.u-aizu.ac.jp/courses/lesson/2/ITP1/6/ITP1_6_C)上で06_Cを提出すると、結果が `PE` となり不正解になっているため、修正をお願いします。
おそらく、`print` 文の箇所でエラーが起きていると思われます。

[AOJ](https://onlinejudge.u-aizu.ac.jp/courses/lesson/2/ITP1/6/ITP1_6_C)上でコードを提出して、結果が`AC`となることを確認するようにお願いします。

2022-12-02 13:47 UTC, takeshun256 reviewed
[File changed](https://github.com/koma757/Basic-Python/pull/2/files)でコードを確認すると、添付画像のように、コードの末尾に赤い警告マークが出ているコードがあると思います。
これは、コードの末尾に空行を1行追加していないことで発生します。
そのため、以下の確認をお願いします。

🔴コードの末尾に、空行が1行挿入されていることを確認してください。


<img width="318" alt="image" src="https://user-images.githubusercontent.com/75155218/205306362-c182cc31-da49-45a3-9d70-3b2c7e3599b2.png">

2022-12-04 01:04 UTC, wataru-dot commented on AOJ/04/04_B.py
> +pi = 3.14159265359
こちらはmathをimportしてpiを使いましょう！

2022-12-06 05:02 UTC, DaichiWarasuga commented
AOJ7確認しました。完璧です。
itertoolsというライブラリを使うと更にコードを短縮できます。もし時間があったら調べてみてください。

2022-12-09 02:26 UTC, DaichiWarasuga commented
AOJ1確認しました。

2022-12-09 11:59 UTC, DaichiWarasuga commented
numpy課題

問題３
ここでは例を実践するのではなく問１で定義したxを使ってXを作ってください。
(やっていることはあっています。)

問題4
処理の内容自体は正しいです。ただnp.dotを使うとコードが煩雑になり見ずらくなります。@演算子を使うことを強く推奨します。

あとコード規約は守りましょう
```
pred_y = w[0]+w[1]*x+w[2]*x**2
pred_y = w[0] + w[1]*x + w[2]*x**2
```

修正後またレビュー依頼を出してください。よろしくお願いします。

2022-12-09 12:41 UTC, takeshun256 approved these changes
03と06の修正を確認しました。
LGTM！

2022-12-09 12:58 UTC, takeshun256 requested changes
pandas課題をレビューしました。以下の2点の修正をお願いします。

🟢問4について、
題意はユニーク数を求める課題なので、`value_counts` で得られたSeriesの長さが求めたいユニーク件数に当たるので、長さを取る処理を加えてください。もしくは、`nunique` を使って直接ユニーク件数を求めることもできます。

🟢問6について、 
下記の `fillna(0)` の処理が `df_merge` へ反映されてないので、今のままでは、 `df_merge` は欠損値が残ったままになっています。
そのため、再代入もしくは、`fillna`のオプションである`inplace`を使って、df_merge を更新してみてください。
```python
#NaNを0に置換
df_merge['amount'].fillna(0)
```

2022-12-12 00:12 UTC, DaichiWarasuga commented
numpy課題

確認しました。素晴らしいです。

2022-12-13 12:04 UTC, takeshun256 approved these changes
pandasの修正をありがとうございます。
LGTM

2022-12-13 12:11 UTC, merged